version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "bot"

    networks:
      - dwld
    volumes:
      - ../bot.yaml:/var/bot.yaml
      - ../bot.db:/var/bot.db


networks:
  dwld:
    driver: bridge
