version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "bot"

    networks:
      - dwld
    volumes:
      - /bot.yaml:/app/bot.yaml


networks:
  dwld:
    driver: bridge
